services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./src:/app
    ports:
      - 1323:1323
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d

volumes:
  pg-data:
