services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./src:/app
    ports:
      - 1323:1323
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d

  test:
    image: testcontainer-demo-api
    command: go test -v ./...
    working_dir: $PWD/src
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host

volumes:
  pg-data:
